export const LANGUAGE_LIST = {
  "Indo-European": {
    Romance: [
      "Catalan",
      "Portuguese",
      "Spanish",
      "Italian",
      "French",
      "Romanian",
      "Ladin",
      "Corsican",
      "Occitan",
    ],
    Germanic: [
      "English",
      "German",
      "Dutch",
      "Afrikaans",
      "Frisian",
      "Danish",
      "Norwegian",
      "Swedish",
      "Luxembourgish",
      "Yiddish",
    ],
    Slavic: [
      "Belarusian",
      "Russian",
      "Bulgarian",
      "Croatian",
      "Czech",
      "Slovak",
      "Slovene",
      "Polish",
      "Montenegrin",
      "Serbian",
      "Macedonian",
      "Ukrainian",
      "Rusyn",
    ],
    "Indo-Aryan": [
      "Hindi",
      "Urdu",
      "Bengali",
      "Punjabi",
      "Sindhi",
      "Gujarati",
      "Marathi",
      "Assamese",
      "Maithili",
      "Bhojpuri",
      "Nepali",
      "Konkani",
      "Kashmiri",
      "Odia",
      "Dogri",
    ],
    "Indo-Iranian": ["Persian, Pashto, Kurdish, Tajik, Balochi"],
    Celtic: ["Irish", "Scottish", "Gaelic", "Welsh", "Breton"],
    Armenian: ["Armenian"],
    Albanian: ["Albanian"],
  },
  Uralic: ["Finnish", "Estonian", "Hungarian"],
  "Altaic/Proposed Macrofamily": {
    Turkic: [
      "Turkish",
      "Azerbaijani",
      "Uzbek",
      "Karakalpak",
      "Turkmen",
      "Kazakh",
      "Kyrgyz",
    ],
    Mongolic: ["Mongolian"],
  },
  "Afro-Asiatic": {
    Semitic: ["Arabic", "Hebrew", "Maltese", "Tigrinya", "Amharic"],
    Berber: ["Tamazight"],
    Chadic: ["Hausa"],
  },
  "Sino-Tibetan": [
    "Mandarin Chinese",
    "Cantonese",
    "Tibetan",
    "Burmese",
    "Dzongkha",
  ],
  "Niger-Congo": {
    Bantu: [
      "Bantu languages",
      "Swahili",
      "Lingala",
      "Kikongo",
      "Zulu",
      "Xhosa",
      "Sotho",
      "Venda",
      "Tswana",
      "Tsonga",
      "Chewa",
      "Chibarwe",
      "Kalanga",
      "Khoisan",
      "Nambya",
      "Ndau",
      "Ndebele",
      "Shangani",
      "Shona",
      "Tonga",
    ],
    Other: ["Yoruba", "Igbo", "Chichewa"],
  },
  Dravidian: ["Tamil", "Kannada", "Malayalam"],
  Austroasiatic: ["Khmer", "Vietnamese"],
  Austronesian: [
    "Fijian",
    "Samoan",
    "Maori",
    "Tagalog/Filipino",
    "Malagasy",
    "Tongan",
    "Malay",
    "Javanese",
    "Sundanese",
  ],
  "Other Native and Regional": {
    "Native American": ["Quechua", "Guarani", "Aymara", "Shuar"],
    "Pama-Nyungan": ["Nyulnyulan", "Worrorran", "Bunuban", "Jarrakan"],
    Caucasian: ["Georgian"],
  },
  "Isolate or Unclassified": ["Basque", "Dhivehi"],
  "Creoles and Pidgins": [
    "Antiguan and Barbudan Creole",
    "Haitian Creole",
    "Seychellois Creole",
    "Cape Verdean Creole",
    "Jamaican Patois",
    "Limonese Creole",
    "Tok Pisin",
  ],
  Other: ["Armenian Sign Language", "Romani"],
};
