/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["1Sea"]: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane009_1: THREE.Mesh;
    Plane009_2: THREE.Mesh;
    Plane009_3: THREE.Mesh;
    Plane009_4: THREE.Mesh;
    Afghanistan: THREE.Mesh;
    Albenia: THREE.Mesh;
    Algeria: THREE.Mesh;
    Angola: THREE.Mesh;
    Argentina: THREE.Mesh;
    Armenia: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane010_1: THREE.Mesh;
    Austria: THREE.Mesh;
    Azerbaijan: THREE.Mesh;
    Bangladesh: THREE.Mesh;
    Belarus: THREE.Mesh;
    Belgium: THREE.Mesh;
    Belize: THREE.Mesh;
    Benin: THREE.Mesh;
    Bhutan: THREE.Mesh;
    Bolivia: THREE.Mesh;
    Bosnia_and_Herzegovina: THREE.Mesh;
    Botswana: THREE.Mesh;
    Brazil: THREE.Mesh;
    Brunei: THREE.Mesh;
    Bulgaria: THREE.Mesh;
    Burkina_Faso: THREE.Mesh;
    Burundi: THREE.Mesh;
    Cabinda: THREE.Mesh;
    Cameroon: THREE.Mesh;
    Canada: THREE.Mesh;
    Central_African_Republic: THREE.Mesh;
    Chad: THREE.Mesh;
    Antarctica: THREE.Mesh;
    Chile: THREE.Mesh;
    China: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Color 1"]: THREE.MeshStandardMaterial;
    ["Color 2"]: THREE.MeshStandardMaterial;
    ["Color 3"]: THREE.MeshStandardMaterial;
    ["Color 4"]: THREE.MeshStandardMaterial;
    Color5: THREE.MeshStandardMaterial;
    Antartika: THREE.MeshStandardMaterial;
  };
};

export function WorldMap2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/world_map_semiseparated.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1Sea"].geometry}
        material={materials.Material}
        position={[0.292, 0, -0.004]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[4.971, 2.616, 2.616]}
      />
      {/* <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials["Color 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials["Color 2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_2.geometry}
          material={materials["Color 3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_3.geometry}
          material={materials["Color 4"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_4.geometry}
          material={materials.Color5}
        />
      </group> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Afghanistan.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Albenia.geometry}
        material={nodes.Albenia.material}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Algeria.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Angola.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Argentina.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Armenia.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials["Color 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={materials["Color 2"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Austria.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Azerbaijan.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bangladesh.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Belarus.geometry}
        material={nodes.Belarus.material}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Belgium.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Belize.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Benin.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bhutan.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolivia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bosnia_and_Herzegovina.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Botswana.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazil.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brunei.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulgaria.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Burkina_Faso.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Burundi.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cabinda.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cameroon.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canada.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Central_African_Republic.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chad.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Antarctica.geometry}
        material={materials.Antartika}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chile.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.China.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
    </group>
  );
}

useGLTF.preload("/models/world_map_semiseparated.glb");
