/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ercandinsel (https://sketchfab.com/ercandinsel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2d-world-map-with-countries-74192acdc7a949f8bdae478d5da3ac6c
Title: 2D World Map With Countries 
*/

import * as THREE from "three";
import React, { useContext, useEffect, useRef } from "react";
import { TransformControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import HeatmapScaling from "@/lib/heatmapScaling";
import { invalidate, useFrame } from "@react-three/fiber";
import { ScoreContext } from "@/app/ScoreProvider";

type GLTFResult = GLTF & {
  nodes: {
    Afghanistan: THREE.Mesh;
    Albenia: THREE.Mesh;
    Algeria: THREE.Mesh;
    Angola: THREE.Mesh;
    Antarctica: THREE.Mesh;
    Argentina: THREE.Mesh;
    Armenia: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Austria: THREE.Mesh;
    Azerbaijan: THREE.Mesh;
    Bangladesh: THREE.Mesh;
    Belarus: THREE.Mesh;
    Belgium: THREE.Mesh;
    Belize: THREE.Mesh;
    Benin: THREE.Mesh;
    Bhutan: THREE.Mesh;
    Bolivia: THREE.Mesh;
    Bosnia_and_Herzegovina: THREE.Mesh;
    Botswana: THREE.Mesh;
    Brazil: THREE.Mesh;
    Brunei: THREE.Mesh;
    Bulgaria: THREE.Mesh;
    Burkina_Faso: THREE.Mesh;
    Burundi: THREE.Mesh;
    Cabinda: THREE.Mesh;
    Cameroon: THREE.Mesh;
    Canada: THREE.Mesh;
    Central_African_Republic: THREE.Mesh;
    Chad: THREE.Mesh;
    Chile: THREE.Mesh;
    China: THREE.Mesh;
    Colombia: THREE.Mesh;
    Cambodia: THREE.Mesh;
    Republic_of_the_Congo: THREE.Mesh;
    Ivory_Coast: THREE.Mesh;
    Cuba: THREE.Mesh;
    Czechia: THREE.Mesh;
    DR_Congo: THREE.Mesh;
    Denmark: THREE.Mesh;
    Djibouti: THREE.Mesh;
    Dominican_Republic: THREE.Mesh;
    ["Timor-Leste"]: THREE.Mesh;
    Ecuador: THREE.Mesh;
    Egypt: THREE.Mesh;
    El_Salvador: THREE.Mesh;
    Equatorial_Guinea: THREE.Mesh;
    Eritrea: THREE.Mesh;
    Estonia: THREE.Mesh;
    Ethiopia: THREE.Mesh;
    Plane052: THREE.Mesh;
    Plane052_1: THREE.Mesh;
    Fiji: THREE.Mesh;
    Finland: THREE.Mesh;
    France: THREE.Mesh;
    French_Guiana: THREE.Mesh;
    Gabon: THREE.Mesh;
    Georgia: THREE.Mesh;
    Germany: THREE.Mesh;
    Ghana: THREE.Mesh;
    Greece: THREE.Mesh;
    Greenland: THREE.Mesh;
    Guatemala: THREE.Mesh;
    Guinea: THREE.Mesh;
    ["Guinea-Bissau"]: THREE.Mesh;
    Guyana: THREE.Mesh;
    Haiti: THREE.Mesh;
    Hawaii: THREE.Mesh;
    Honduras: THREE.Mesh;
    Hungary: THREE.Mesh;
    Iceland: THREE.Mesh;
    India: THREE.Mesh;
    Indonesia: THREE.Mesh;
    Iraq: THREE.Mesh;
    Ireland: THREE.Mesh;
    Israel: THREE.Mesh;
    Italy: THREE.Mesh;
    Jamaica: THREE.Mesh;
    Japan: THREE.Mesh;
    Jordan: THREE.Mesh;
    Kazakhstan: THREE.Mesh;
    Kenya: THREE.Mesh;
    Kyrgyzstan: THREE.Mesh;
    Kosovo: THREE.Mesh;
    Kuwait: THREE.Mesh;
    Laos: THREE.Mesh;
    Latvia: THREE.Mesh;
    Lebanon: THREE.Mesh;
    Lesotho: THREE.Mesh;
    Liberia: THREE.Mesh;
    Libya: THREE.Mesh;
    Liechtenstein: THREE.Mesh;
    Lithuania: THREE.Mesh;
    Macedonia: THREE.Mesh;
    Madagascar: THREE.Mesh;
    Malawi: THREE.Mesh;
    Malaysia: THREE.Mesh;
    Mali: THREE.Mesh;
    Mauritania: THREE.Mesh;
    Mauritius: THREE.Mesh;
    Mexico: THREE.Mesh;
    Moldova: THREE.Mesh;
    Mongolia: THREE.Mesh;
    Montenegro: THREE.Mesh;
    Morocco: THREE.Mesh;
    Mozambique: THREE.Mesh;
    Myanmar: THREE.Mesh;
    Namibia: THREE.Mesh;
    Nepal: THREE.Mesh;
    Netherlands: THREE.Mesh;
    New_Caledonia: THREE.Mesh;
    New_Zealand: THREE.Mesh;
    Nicaragua: THREE.Mesh;
    Niger: THREE.Mesh;
    Nigeria: THREE.Mesh;
    Northern_Cyprus: THREE.Mesh;
    North_Korea: THREE.Mesh;
    Plane118: THREE.Mesh;
    Plane118_1: THREE.Mesh;
    Oman: THREE.Mesh;
    Pakistan: THREE.Mesh;
    Palestine: THREE.Mesh;
    Panama: THREE.Mesh;
    Papua_New_Guinea: THREE.Mesh;
    Paraguay: THREE.Mesh;
    Peru: THREE.Mesh;
    Philippines: THREE.Mesh;
    Poland: THREE.Mesh;
    Puerto_Rico: THREE.Mesh;
    Portugal: THREE.Mesh;
    Qatar: THREE.Mesh;
    Reunion: THREE.Mesh;
    Romania: THREE.Mesh;
    Plane133: THREE.Mesh;
    Plane133_1: THREE.Mesh;
    Rwanda: THREE.Mesh;
    Costa_Rica: THREE.Mesh;
    Saudi_Arabia: THREE.Mesh;
    Senegal: THREE.Mesh;
    Serbia: THREE.Mesh;
    Sierra_Leone: THREE.Mesh;
    Singapore: THREE.Mesh;
    Slovakia: THREE.Mesh;
    Slovenia: THREE.Mesh;
    Solomon_Islands: THREE.Mesh;
    Somalia: THREE.Mesh;
    South_Africa: THREE.Mesh;
    Cyprus: THREE.Mesh;
    South_Korea: THREE.Mesh;
    South_Korea001: THREE.Mesh;
    Spain: THREE.Mesh;
    Sri_Lanka: THREE.Mesh;
    Sudan: THREE.Mesh;
    Suriname: THREE.Mesh;
    Swaziland: THREE.Mesh;
    Switzerland: THREE.Mesh;
    Sweden: THREE.Mesh;
    Croatia: THREE.Mesh;
    Syria: THREE.Mesh;
    Tajikistan: THREE.Mesh;
    Taiwan: THREE.Mesh;
    Tanzania: THREE.Mesh;
    Thailand: THREE.Mesh;
    Bahamas: THREE.Mesh;
    Gambia: THREE.Mesh;
    Togo: THREE.Mesh;
    Trinidad_and_Tobago: THREE.Mesh;
    Tunisia: THREE.Mesh;
    Turkey: THREE.Mesh;
    Turkmenistan: THREE.Mesh;
    Uganda: THREE.Mesh;
    Ukraine: THREE.Mesh;
    United_Arab_Emirates: THREE.Mesh;
    United_States: THREE.Mesh;
    Uruguay: THREE.Mesh;
    Uzbekistan: THREE.Mesh;
    Vanuatu: THREE.Mesh;
    Venezuela: THREE.Mesh;
    Vietnam: THREE.Mesh;
    Western_Saharah: THREE.Mesh;
    Plane182: THREE.Mesh;
    Plane182_1: THREE.Mesh;
    Zambia: THREE.Mesh;
    Zimbabwe: THREE.Mesh;
    Iran: THREE.Mesh;
  };
  materials: {
    ["Color 2"]: THREE.MeshStandardMaterial;
    Color5: THREE.MeshStandardMaterial;
    ["Color 1"]: THREE.MeshStandardMaterial;
    Antartika: THREE.MeshStandardMaterial;
    ["Color 3"]: THREE.MeshStandardMaterial;
    ["Color 4"]: THREE.MeshStandardMaterial;
  };
};

export function WorldMap(
  props: JSX.IntrinsicElements["group"] & { material: THREE.Material },
) {
  const { score } = useContext(ScoreContext);
  const { nodes, materials } = useGLTF("/models/worldmap.glb") as GLTFResult;
  const group = useRef<THREE.Group>(null!);

  const material = materials.Color5.clone();
  material.emissive = new THREE.Color(0.3, 0.25, 0.25);
  material.emissiveIntensity = 0.1;
  material.toneMapped = false;

  useEffect(() => {
    /**
     * Example of Scores Data
     */
    const scores = new Map<string, number>();
    scores.set(score.country, score.score);

    scores.forEach((value, key) => {
      group.current.traverse((child) => {
        if (child instanceof THREE.Mesh && child.name === key) {
          const { red, green, blue, intensity } = HeatmapScaling(value);
          child.material.emissive.setRGB(red, green, blue);
          child.material.emissiveIntensity = intensity;
          invalidate();
        } else if (child instanceof THREE.Group && child.name === key) {
          child.traverse((child) => {
            if (child instanceof THREE.Mesh) {
              const { red, green, blue, intensity } = HeatmapScaling(value);
              child.material.emissive.setRGB(red, green, blue);
              child.material.emissiveIntensity = intensity;
              invalidate();
            }
          });
        }
      });
    });
  }, [score]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Afghanistan"
        geometry={nodes.Afghanistan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Albenia"
        geometry={nodes.Albenia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Algeria"
        geometry={nodes.Algeria.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Andorra"
        material={material.clone()}
        position={[0.01, 1.03, 0.01]}
        scale={0.018}
      >
        <planeGeometry args={[1, 1]} />
      </mesh>
      <mesh
        name="Angola"
        geometry={nodes.Angola.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Antigua_and_Barbuda"
        material={material.clone()}
        position={[-1.7, 0.26, 0.01]}
        scale={0.018}
      >
        <planeGeometry args={[0.5, 0.5]} />
      </mesh>
      <mesh
        name="Argentina"
        geometry={nodes.Argentina.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Armenia"
        geometry={nodes.Armenia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        name="Australia"
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh geometry={nodes.Plane011.geometry} material={material.clone()} />
        <mesh
          geometry={nodes.Plane011_1.geometry}
          material={material.clone()}
        />
      </group>
      <mesh
        name="Austria"
        geometry={nodes.Austria.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Azerbaijan"
        geometry={nodes.Azerbaijan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Bahamas"
        geometry={nodes.Bahamas.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Bahrain"
        material={material.clone()}
        position={[1.335, 0.525, 0.01]}
        scale={0.018}
      >
        <planeGeometry args={[0.25, 0.5]} />
      </mesh>
      <mesh
        name="Bangladesh"
        geometry={nodes.Bangladesh.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Barbados"
        material={material.clone()}
        position={[-1.62, 0.15, 0.01]}
        scale={0.018}
      >
        <planeGeometry args={[0.5, 0.2]} />
      </mesh>
      <mesh
        name="Belarus"
        geometry={nodes.Belarus.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Belgium"
        geometry={nodes.Belgium.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Belize"
        geometry={nodes.Belize.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Benin"
        geometry={nodes.Benin.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Bhutan"
        geometry={nodes.Bhutan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Bolivia"
        geometry={nodes.Bolivia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Bosnia_and_Herzegovina"
        geometry={nodes.Bosnia_and_Herzegovina.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Botswana"
        geometry={nodes.Botswana.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Brazil"
        geometry={nodes.Brazil.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Brunei"
        geometry={nodes.Brunei.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Bulgaria"
        geometry={nodes.Bulgaria.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Burkina_Faso"
        geometry={nodes.Burkina_Faso.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Burundi"
        geometry={nodes.Burundi.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group name="Cabo_Verde" position={[-0.62, 0.28, 0.01]} scale={0.018}>
        <mesh material={material.clone()} rotation-z={-0.8}>
          <planeGeometry args={[0.6, 0.3]} />
        </mesh>
        <mesh
          material={material.clone()}
          position={[0.8, -1.2, 0]}
          rotation-z={1.1}
        >
          <planeGeometry args={[1, 0.2]} />
        </mesh>
      </group>
      <mesh
        name="Cabinda"
        geometry={nodes.Cabinda.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Cambodia"
        geometry={nodes.Cambodia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Cameroon"
        geometry={nodes.Cameroon.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Canada"
        geometry={nodes.Canada.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Central_African_Republic"
        geometry={nodes.Central_African_Republic.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Chad"
        geometry={nodes.Chad.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Chile"
        geometry={nodes.Chile.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="China"
        geometry={nodes.China.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Colombia"
        geometry={nodes.Colombia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Comoros"
        material={material.clone()}
        position={[1.18, -0.7, 0.01]}
        rotation-z={-0.5}
        scale={0.018}
      >
        <planeGeometry args={[1, 0.2]} />
      </mesh>
      <mesh
        name="Costa_Rica"
        geometry={nodes.Costa_Rica.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Croatia"
        geometry={nodes.Croatia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Cuba"
        geometry={nodes.Cuba.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        name="Cyprus"
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh geometry={nodes.Cyprus.geometry} material={material.clone()} />
        <mesh
          geometry={nodes.Northern_Cyprus.geometry}
          material={material.clone()}
        ></mesh>
      </group>
      <mesh
        name="Czechia"
        geometry={nodes.Czechia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Denmark"
        geometry={nodes.Denmark.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Djibouti"
        geometry={nodes.Djibouti.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Dominica"
        material={material.clone()}
        position={[-1.67, 0.19, 0.01]}
        scale={0.018}
      >
        <planeGeometry args={[0.4, 0.5]} />
      </mesh>
      <mesh
        name="Dominican_Republic"
        geometry={nodes.Dominican_Republic.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="DR_Congo"
        geometry={nodes.DR_Congo.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Ecuador"
        geometry={nodes.Ecuador.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Egypt"
        geometry={nodes.Egypt.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="El_Salvador"
        geometry={nodes.El_Salvador.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Equatorial_Guinea"
        geometry={nodes.Equatorial_Guinea.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Eritrea"
        geometry={nodes.Eritrea.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Estonia"
        geometry={nodes.Estonia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Eswatini"
        geometry={nodes.Swaziland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Ethiopia"
        geometry={nodes.Ethiopia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Fiji"
        geometry={nodes.Fiji.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Finland"
        geometry={nodes.Finland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="France"
        geometry={nodes.France.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="French_Guiana"
        geometry={nodes.French_Guiana.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Gabon"
        geometry={nodes.Gabon.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Gambia"
        geometry={nodes.Gambia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Georgia"
        geometry={nodes.Georgia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Germany"
        geometry={nodes.Germany.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Ghana"
        geometry={nodes.Ghana.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Greece"
        geometry={nodes.Greece.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Grenada"
        material={material.clone()}
        position={[-1.67, 0.11, 0.01]}
        rotation-z={-0.2}
        scale={0.018}
      >
        <planeGeometry args={[0.3, 0.6]} />
      </mesh>
      <mesh
        name="Greenland"
        geometry={nodes.Greenland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Guatemala"
        geometry={nodes.Guatemala.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Guinea"
        geometry={nodes.Guinea.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Guinea-Bissau"
        geometry={nodes["Guinea-Bissau"].geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Guyana"
        geometry={nodes.Guyana.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Haiti"
        geometry={nodes.Haiti.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Hawaii"
        geometry={nodes.Hawaii.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Honduras"
        geometry={nodes.Honduras.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Hungary"
        geometry={nodes.Hungary.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Iceland"
        geometry={nodes.Iceland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="India"
        geometry={nodes.India.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Indonesia"
        geometry={nodes.Indonesia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Iraq"
        geometry={nodes.Iraq.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Ireland"
        geometry={nodes.Ireland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Israel"
        geometry={nodes.Israel.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Italy"
        geometry={nodes.Italy.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Ivory_Coast"
        geometry={nodes.Ivory_Coast.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Jamaica"
        geometry={nodes.Jamaica.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Japan"
        geometry={nodes.Japan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
        onClick={() => console.log("japan")}
      />
      <mesh
        name="Jordan"
        geometry={nodes.Jordan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Kazakhstan"
        geometry={nodes.Kazakhstan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Kenya"
        geometry={nodes.Kenya.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group name="Kiribati" position={[4.55, -0.4, 0.01]} scale={0.018}>
        <mesh material={material.clone()} rotation-z={-1}>
          <planeGeometry args={[2, 0.1]} />
        </mesh>
        <mesh position={[3.5, -2.5, 0]} material={material.clone()}>
          <planeGeometry args={[0.9, 0.1]} />
        </mesh>
        <mesh
          position={[6, 1, 0]}
          rotation-z={-1.2}
          material={material.clone()}
        >
          <planeGeometry args={[1.2, 0.1]} />
        </mesh>
      </group>
      <mesh
        name="Kuwait"
        geometry={nodes.Kuwait.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Kyrgyzstan"
        geometry={nodes.Kyrgyzstan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Kosovo"
        geometry={nodes.Kosovo.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Laos"
        geometry={nodes.Laos.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Latvia"
        geometry={nodes.Latvia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Lebanon"
        geometry={nodes.Lebanon.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Lesotho"
        geometry={nodes.Lesotho.geometry}
        material={material.clone()}
        position={[0.673, 1, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Liberia"
        geometry={nodes.Liberia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Libya"
        geometry={nodes.Libya.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Liechtenstein"
        geometry={nodes.Liechtenstein.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Lithuania"
        geometry={nodes.Lithuania.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Luxembourg"
        material={material.clone()}
        position={[0.135, 1.244, 0.1]}
        scale={0.018}
      >
        <planeGeometry args={[0.7, 1]} />
      </mesh>
      <mesh
        name="Madagascar"
        geometry={nodes.Madagascar.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Malawi"
        geometry={nodes.Malawi.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Malaysia"
        geometry={nodes.Malaysia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Mali"
        geometry={nodes.Mali.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Mauritania"
        geometry={nodes.Mauritania.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Mauritius"
        geometry={nodes.Mauritius.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Mexico"
        geometry={nodes.Mexico.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Moldova"
        geometry={nodes.Moldova.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Mongolia"
        geometry={nodes.Mongolia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Montenegro"
        geometry={nodes.Montenegro.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Morocco"
        geometry={nodes.Morocco.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Mozambique"
        geometry={nodes.Mozambique.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Myanmar"
        geometry={nodes.Myanmar.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Namibia"
        geometry={nodes.Namibia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Nepal"
        geometry={nodes.Nepal.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Netherlands"
        geometry={nodes.Netherlands.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="New_Caledonia"
        geometry={nodes.New_Caledonia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="New_Zealand"
        geometry={nodes.New_Zealand.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Nicaragua"
        geometry={nodes.Nicaragua.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Niger"
        geometry={nodes.Niger.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Nigeria"
        geometry={nodes.Nigeria.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="North_Korea"
        geometry={nodes.North_Korea.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="North_Macedonia"
        geometry={nodes.Macedonia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        name="Norway"
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh geometry={nodes.Plane118.geometry} material={material.clone()} />
        <mesh
          geometry={nodes.Plane118_1.geometry}
          material={material.clone()}
        />
      </group>
      <mesh
        name="Oman"
        geometry={nodes.Oman.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Pakistan"
        geometry={nodes.Pakistan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Palestine"
        geometry={nodes.Palestine.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Panama"
        geometry={nodes.Panama.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Papua_New_Guinea"
        geometry={nodes.Papua_New_Guinea.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Paraguay"
        geometry={nodes.Paraguay.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Peru"
        geometry={nodes.Peru.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Philippines"
        geometry={nodes.Philippines.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Poland"
        geometry={nodes.Poland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Puerto_Rico"
        geometry={nodes.Puerto_Rico.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Portugal"
        geometry={nodes.Portugal.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Qatar"
        geometry={nodes.Qatar.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Republic_of_the_Congo"
        geometry={nodes.Republic_of_the_Congo.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Reunion"
        geometry={nodes.Reunion.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Romania"
        geometry={nodes.Romania.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        name="Russia"
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh geometry={nodes.Plane133.geometry} material={material.clone()} />
        <mesh
          geometry={nodes.Plane133_1.geometry}
          material={material.clone()}
        />
      </group>
      <mesh
        name="Rwanda"
        geometry={nodes.Rwanda.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Saudi_Arabia"
        geometry={nodes.Saudi_Arabia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Senegal"
        geometry={nodes.Senegal.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Serbia"
        geometry={nodes.Serbia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Sierra_Leone"
        geometry={nodes.Sierra_Leone.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Singapore"
        geometry={nodes.Singapore.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Slovakia"
        geometry={nodes.Slovakia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Slovenia"
        geometry={nodes.Slovenia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Solomon_Islands"
        geometry={nodes.Solomon_Islands.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Somalia"
        geometry={nodes.Somalia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="South_Africa"
        geometry={nodes.South_Africa.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="South_Korea"
        geometry={nodes.South_Korea.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="South_Sudan"
        geometry={nodes.South_Korea001.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Spain"
        geometry={nodes.Spain.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Sri_Lanka"
        geometry={nodes.Sri_Lanka.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Sudan"
        geometry={nodes.Sudan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Suriname"
        geometry={nodes.Suriname.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Switzerland"
        geometry={nodes.Switzerland.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        name="Sweden"
        geometry={nodes.Sweden.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Syria"
        geometry={nodes.Syria.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Tajikistan"
        geometry={nodes.Tajikistan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Taiwan"
        geometry={nodes.Taiwan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Tanzania"
        geometry={nodes.Tanzania.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Thailand"
        geometry={nodes.Thailand.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Timor-Leste"
        geometry={nodes["Timor-Leste"].geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Togo"
        geometry={nodes.Togo.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Trinidad_and_Tobago"
        geometry={nodes.Trinidad_and_Tobago.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Tunisia"
        geometry={nodes.Tunisia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Turkey"
        geometry={nodes.Turkey.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Turkmenistan"
        geometry={nodes.Turkmenistan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Uganda"
        geometry={nodes.Uganda.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Ukraine"
        geometry={nodes.Ukraine.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="United_Arab_Emirates"
        geometry={nodes.United_Arab_Emirates.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="United_Kingdom"
        geometry={nodes.Plane052.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="United_States"
        geometry={nodes.United_States.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Uruguay"
        geometry={nodes.Uruguay.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Uzbekistan"
        geometry={nodes.Uzbekistan.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Vanuatu"
        geometry={nodes.Vanuatu.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Venezuela"
        geometry={nodes.Venezuela.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Vietnam"
        geometry={nodes.Vietnam.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Western_Saharah"
        geometry={nodes.Western_Saharah.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Yemen"
        geometry={nodes.Plane182_1.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Zambia"
        geometry={nodes.Zambia.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Zimbabwe"
        geometry={nodes.Zimbabwe.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        name="Iran"
        geometry={nodes.Iran.geometry}
        material={material.clone()}
        position={[0.673, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
    </group>
  );
}

useGLTF.preload("/models/worldmap.glb");
