/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Afghanistan: THREE.Mesh;
    Albenia: THREE.Mesh;
    Algeria: THREE.Mesh;
    Angola: THREE.Mesh;
    Antarctica: THREE.Mesh;
    Argentina: THREE.Mesh;
    Armenia: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane011_1: THREE.Mesh;
    Austria: THREE.Mesh;
    Azerbaijan: THREE.Mesh;
    Bangladesh: THREE.Mesh;
    Belarus: THREE.Mesh;
    Belgium: THREE.Mesh;
    Belize: THREE.Mesh;
    Benin: THREE.Mesh;
    Bhutan: THREE.Mesh;
    Bolivia: THREE.Mesh;
    Bosnia_and_Herzegovina: THREE.Mesh;
    Botswana: THREE.Mesh;
    Brazil: THREE.Mesh;
    Brunei: THREE.Mesh;
    Bulgaria: THREE.Mesh;
    Burkina_Faso: THREE.Mesh;
    Burundi: THREE.Mesh;
    Cabinda: THREE.Mesh;
    Cameroon: THREE.Mesh;
    Canada: THREE.Mesh;
    Central_African_Republic: THREE.Mesh;
    Chad: THREE.Mesh;
    Chile: THREE.Mesh;
    China: THREE.Mesh;
    Colombia: THREE.Mesh;
    Cambodia: THREE.Mesh;
    Republic_of_the_Congo: THREE.Mesh;
    Ivory_Coast: THREE.Mesh;
    Cuba: THREE.Mesh;
    Czechia: THREE.Mesh;
    DR_Congo: THREE.Mesh;
    Denmark: THREE.Mesh;
    Djibouti: THREE.Mesh;
    Dominican_Republic: THREE.Mesh;
    ["Timor-Leste"]: THREE.Mesh;
    Ecuador: THREE.Mesh;
    Egypt: THREE.Mesh;
    El_Salvador: THREE.Mesh;
    Equatorial_Guinea: THREE.Mesh;
    Eritrea: THREE.Mesh;
    Estonia: THREE.Mesh;
    Ethiopia: THREE.Mesh;
    Plane052: THREE.Mesh;
    Plane052_1: THREE.Mesh;
    Fiji: THREE.Mesh;
    Finland: THREE.Mesh;
    France: THREE.Mesh;
    French_Guiana: THREE.Mesh;
    Gabon: THREE.Mesh;
    Georgia: THREE.Mesh;
    Germany: THREE.Mesh;
    Ghana: THREE.Mesh;
    Greece: THREE.Mesh;
    Greenland: THREE.Mesh;
    Guatemala: THREE.Mesh;
    Guinea: THREE.Mesh;
    ["Guinea-Bissau"]: THREE.Mesh;
    Guyana: THREE.Mesh;
    Haiti: THREE.Mesh;
    Hawaii: THREE.Mesh;
    Honduras: THREE.Mesh;
    Hungary: THREE.Mesh;
    Iceland: THREE.Mesh;
    India: THREE.Mesh;
    Indonesia: THREE.Mesh;
    Iraq: THREE.Mesh;
    Ireland: THREE.Mesh;
    Israel: THREE.Mesh;
    Italy: THREE.Mesh;
    Jamaica: THREE.Mesh;
    Japan: THREE.Mesh;
    Jordan: THREE.Mesh;
    Kazakhstan: THREE.Mesh;
    Kenya: THREE.Mesh;
    Kyrgyzstan: THREE.Mesh;
    Kosovo: THREE.Mesh;
    Kuwait: THREE.Mesh;
    Laos: THREE.Mesh;
    Latvia: THREE.Mesh;
    Lebanon: THREE.Mesh;
    Lesotho: THREE.Mesh;
    Liberia: THREE.Mesh;
    Libya: THREE.Mesh;
    Liechtenstein: THREE.Mesh;
    Lithuania: THREE.Mesh;
    Macedonia: THREE.Mesh;
    Madagascar: THREE.Mesh;
    Malawi: THREE.Mesh;
    Malaysia: THREE.Mesh;
    Mali: THREE.Mesh;
    Mauritania: THREE.Mesh;
    Mauritius: THREE.Mesh;
    Mexico: THREE.Mesh;
    Moldova: THREE.Mesh;
    Mongolia: THREE.Mesh;
    Montenegro: THREE.Mesh;
    Morocco: THREE.Mesh;
    Mozambique: THREE.Mesh;
    Myanmar: THREE.Mesh;
    Namibia: THREE.Mesh;
    Nepal: THREE.Mesh;
    Netherlands: THREE.Mesh;
    New_Caledonia: THREE.Mesh;
    New_Zealand: THREE.Mesh;
    Nicaragua: THREE.Mesh;
    Niger: THREE.Mesh;
    Nigeria: THREE.Mesh;
    Northern_Cyprus: THREE.Mesh;
    North_Korea: THREE.Mesh;
    Plane118: THREE.Mesh;
    Plane118_1: THREE.Mesh;
    Oman: THREE.Mesh;
    Pakistan: THREE.Mesh;
    Palestine: THREE.Mesh;
    Panama: THREE.Mesh;
    Papua_New_Guinea: THREE.Mesh;
    Paraguay: THREE.Mesh;
    Peru: THREE.Mesh;
    Philippines: THREE.Mesh;
    Poland: THREE.Mesh;
    Puerto_Rico: THREE.Mesh;
    Portugal: THREE.Mesh;
    Qatar: THREE.Mesh;
    Reunion: THREE.Mesh;
    Romania: THREE.Mesh;
    Plane133: THREE.Mesh;
    Plane133_1: THREE.Mesh;
    Rwanda: THREE.Mesh;
    Costa_Rica: THREE.Mesh;
    Saudi_Arabia: THREE.Mesh;
    Senegal: THREE.Mesh;
    Serbia: THREE.Mesh;
    Sierra_Leone: THREE.Mesh;
    Singapore: THREE.Mesh;
    Slovakia: THREE.Mesh;
    Slovenia: THREE.Mesh;
    Solomon_Islands: THREE.Mesh;
    Somalia: THREE.Mesh;
    South_Africa: THREE.Mesh;
    Cyprus: THREE.Mesh;
    South_Korea: THREE.Mesh;
    South_Korea001: THREE.Mesh;
    Spain: THREE.Mesh;
    Sri_Lanka: THREE.Mesh;
    Sudan: THREE.Mesh;
    Suriname: THREE.Mesh;
    Swaziland: THREE.Mesh;
    Switzerland: THREE.Mesh;
    Sweden: THREE.Mesh;
    Croatia: THREE.Mesh;
    Syria: THREE.Mesh;
    Tajikistan: THREE.Mesh;
    Taiwan: THREE.Mesh;
    Tanzania: THREE.Mesh;
    Thailand: THREE.Mesh;
    Bahamas: THREE.Mesh;
    Gambia: THREE.Mesh;
    Togo: THREE.Mesh;
    Trinidad_and_Tobago: THREE.Mesh;
    Tunisia: THREE.Mesh;
    Turkey: THREE.Mesh;
    Turkmenistan: THREE.Mesh;
    Uganda: THREE.Mesh;
    Ukraine: THREE.Mesh;
    United_Arab_Emirates: THREE.Mesh;
    United_States: THREE.Mesh;
    Uruguay: THREE.Mesh;
    Uzbekistan: THREE.Mesh;
    Vanuatu: THREE.Mesh;
    Venezuela: THREE.Mesh;
    Vietnam: THREE.Mesh;
    Western_Saharah: THREE.Mesh;
    Plane182: THREE.Mesh;
    Plane182_1: THREE.Mesh;
    Zambia: THREE.Mesh;
    Zimbabwe: THREE.Mesh;
    Iran: THREE.Mesh;
  };
  materials: {
    ["Color 2"]: THREE.MeshStandardMaterial;
    Color5: THREE.MeshStandardMaterial;
    ["Color 1"]: THREE.MeshStandardMaterial;
    Antartika: THREE.MeshStandardMaterial;
    ["Color 3"]: THREE.MeshStandardMaterial;
    ["Color 4"]: THREE.MeshStandardMaterial;
  };
};

export function WorldMap2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/worldmap.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Afghanistan.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Albenia.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Algeria.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Angola.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Antarctica.geometry}
        material={materials.Antartika}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Argentina.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Armenia.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials["Color 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials["Color 2"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Austria.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Azerbaijan.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bangladesh.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Belarus.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Belgium.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Belize.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Benin.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bhutan.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolivia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bosnia_and_Herzegovina.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Botswana.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazil.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brunei.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bulgaria.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Burkina_Faso.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Burundi.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cabinda.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cameroon.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canada.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Central_African_Republic.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chad.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chile.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.China.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Colombia.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cambodia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Republic_of_the_Congo.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivory_Coast.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cuba.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Czechia.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DR_Congo.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Denmark.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Djibouti.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dominican_Republic.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Timor-Leste"].geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ecuador.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Egypt.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.El_Salvador.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Equatorial_Guinea.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Eritrea.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Estonia.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ethiopia.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane052.geometry}
          material={materials["Color 2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane052_1.geometry}
          material={materials["Color 3"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fiji.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Finland.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.France.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.French_Guiana.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gabon.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Georgia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Germany.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ghana.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Greece.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Greenland.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Guatemala.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Guinea.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Guinea-Bissau"].geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Guyana.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Haiti.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hawaii.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Honduras.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hungary.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Iceland.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.India.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Indonesia.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Iraq.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ireland.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Israel.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Italy.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Jamaica.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Japan.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Jordan.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kazakhstan.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kenya.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kyrgyzstan.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kosovo.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kuwait.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Laos.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Latvia.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lebanon.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lesotho.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Liberia.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Libya.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Liechtenstein.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lithuania.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Macedonia.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Madagascar.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Malawi.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Malaysia.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mali.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mauritania.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mauritius.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mexico.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moldova.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mongolia.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Montenegro.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Morocco.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mozambique.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Myanmar.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Namibia.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nepal.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Netherlands.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.New_Caledonia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.New_Zealand.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nicaragua.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Niger.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nigeria.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Northern_Cyprus.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.North_Korea.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane118.geometry}
          material={materials["Color 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane118_1.geometry}
          material={materials["Color 2"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Oman.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pakistan.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palestine.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Panama.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Papua_New_Guinea.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paraguay.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Peru.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Philippines.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Poland.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Puerto_Rico.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portugal.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Qatar.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Reunion.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Romania.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane133.geometry}
          material={materials["Color 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane133_1.geometry}
          material={materials["Color 3"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rwanda.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Costa_Rica.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Saudi_Arabia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Senegal.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Serbia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sierra_Leone.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Singapore.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Slovakia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Slovenia.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Solomon_Islands.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Somalia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.South_Africa.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cyprus.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.South_Korea.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.South_Korea001.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spain.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sri_Lanka.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sudan.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suriname.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Swaziland.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switzerland.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sweden.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Croatia.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Syria.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tajikistan.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taiwan.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tanzania.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thailand.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bahamas.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gambia.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Togo.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trinidad_and_Tobago.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tunisia.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Turkey.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Turkmenistan.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Uganda.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ukraine.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.United_Arab_Emirates.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.United_States.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Uruguay.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Uzbekistan.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vanuatu.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Venezuela.geometry}
        material={materials["Color 2"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vietnam.geometry}
        material={materials["Color 3"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Western_Saharah.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <group
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane182.geometry}
          material={materials["Color 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane182_1.geometry}
          material={materials.Color5}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Zambia.geometry}
        material={materials["Color 4"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Zimbabwe.geometry}
        material={materials.Color5}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Iran.geometry}
        material={materials["Color 1"]}
        position={[0.673, 1.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.018}
      />
    </group>
  );
}

useGLTF.preload("/models/worldmap.glb");
